services:
  db_api:
    build: ./db_api
    container_name: db_api_inf225
    restart: always
    volumes:
      - .:/db_api
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:14
    container_name: db_inf255
    environment:
      POSTGRES_USER: ayds123
      POSTGRES_PASSWORD: ayds123
      POSTGRES_DB: proyecto_db
    ports:
      - "5432:5432"
    volumes:
      - ./db_api/init.sql:/docker-entrypoint-initdb.d/init.sql
